### ISSUE TITLE
Couple questions

### ISSUE THREAD

**Issue by samd1993** [boyuren158/DirFactor-fix#1]
Hi,

Thank you for posting the code. I am curious if this is an updated version of your older version of DirFactor that now includes fixed and random effects? I didn't see anything about mixed effects on your older github. I am very keen on applying something like to my microbiome dataset, especially since I cannot get MIMIX to run for the life of me. I was wondering if there was a more detailed tutorial on running this because I cannot understand the script on its own. 
Cheers,
Sam

**Comment by boyuren158** [comment]
Hi Sam,

Thanks for your interest. This repo contains the version of DirFactor with mixed effects. Unfortunately I don't have a more detailed tutorial at hand. But the function is rather easy to use. You can refer to R/diabimmune_analysis.R for an example. Basically, you just need to have three matrices, one is for the microbiome counts (data.full$data.mt), a covariate matrix (data.full$design.mt) and also a matrix to indicate which subject each sample belongs to (data.full$sub.mt). For the subject specifying matrix, the columns are subject and rows are sample. A cell is one if the sample belongs to that subject and zero otherwise.

Please feel free to let me know if you have more questions regarding the script.

Best,
Boyu

**Comment by samd1993** [comment]
Hi Boyu,

Thanks for the quick response. The analysis script makes a lot more sense. And I see the line where I would replace the three files you've described with my own. I will try it and report back. 
Thanks,
Sam

**Comment by samd1993** [comment]
Another question: the count data looks like it is log transformed? Just want to make sure

**Comment by boyuren158** [comment]
No, you should use the raw counts.

**Comment by samd1993** [comment]
Gotcha thanks
